import type { VercelRequest, VercelResponse } from "@vercel/node";

const HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#090c0b">
  <title>Endurance Bridge — your training data for AI</title>
  <style>
    :root{color-scheme:dark;--bg:#090c0b;--panel:#111614;--panel-2:#161d1a;--line:#27302c;--line-bright:#3b4842;--ink:#f4f7f5;--muted:#909c96;--soft:#c9d1cd;--lime:#c7ff45;--lime-ink:#172000;--red:#ff7474;--radius:22px;--shadow:0 28px 90px rgba(0,0,0,.38)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;background:var(--bg);color:var(--ink);font:15px/1.55 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden}body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(900px 540px at 82% -8%,rgba(199,255,69,.11),transparent 66%),linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:auto,56px 56px,56px 56px;mask-image:linear-gradient(to bottom,#000,transparent 72%)}
    button,input{font:inherit}button{border:0;cursor:pointer}.shell{position:relative;z-index:1;max-width:1160px;margin:auto;padding:0 28px 72px}.topbar{height:84px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08)}.brand{display:flex;align-items:center;gap:12px;font-weight:780;letter-spacing:-.02em}.mark{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:var(--lime);color:var(--lime-ink);font-size:19px;font-weight:900;transform:skew(-7deg)}.topmeta{display:flex;align-items:center;gap:10px}.badge{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:999px;padding:7px 11px;color:var(--muted);font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.badge:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--lime);box-shadow:0 0 14px var(--lime)}
    .hero{display:grid;grid-template-columns:minmax(0,1.12fr) minmax(360px,.88fr);gap:54px;align-items:center;padding:82px 0 54px}.kicker{color:var(--lime);font:750 12px/1 ui-monospace,SFMono-Regular,monospace;text-transform:uppercase;letter-spacing:.14em;margin-bottom:20px}.hero h1{font-size:clamp(54px,7.3vw,92px);line-height:.91;letter-spacing:-.065em;margin:0;max-width:720px}.hero h1 span{color:var(--muted)}.lead{max-width:610px;color:var(--soft);font-size:clamp(17px,2vw,20px);margin:27px 0 0}.proof{display:flex;gap:9px;flex-wrap:wrap;margin-top:30px}.proof span{border:1px solid var(--line);background:rgba(17,22,20,.7);border-radius:9px;padding:8px 10px;color:var(--muted);font:650 12px/1 ui-monospace,SFMono-Regular,monospace}.proof span:before{content:"✓";color:var(--lime);margin-right:7px}
    .visual{position:relative;min-height:445px}.device{position:absolute;inset:0 8px 0 38px;background:linear-gradient(155deg,#1b2420,#0d1210 62%);border:1px solid #344139;border-radius:32px;padding:24px;box-shadow:var(--shadow);transform:rotate(2deg)}.device:before{content:"";position:absolute;inset:10px;border:1px solid rgba(255,255,255,.04);border-radius:24px}.device-head{display:flex;justify-content:space-between;align-items:center;color:var(--muted);font:650 11px/1 ui-monospace,SFMono-Regular,monospace;text-transform:uppercase;letter-spacing:.1em}.device-head i{width:8px;height:8px;border-radius:50%;background:var(--lime);box-shadow:0 0 18px var(--lime)}.metric{margin:55px 0 29px}.metric-label{color:var(--muted);font-size:13px}.metric-value{font-size:65px;line-height:1;letter-spacing:-.06em;font-weight:760;margin-top:6px}.metric-value small{font-size:16px;color:var(--muted);letter-spacing:0;margin-left:7px}.chart{height:102px;display:flex;align-items:end;gap:7px;border-bottom:1px solid var(--line);padding:0 3px}.chart b{display:block;flex:1;min-width:8px;border-radius:5px 5px 0 0;background:linear-gradient(to top,#719527,var(--lime));opacity:.9}.device-row{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px}.mini{background:rgba(255,255,255,.035);border:1px solid var(--line);border-radius:14px;padding:14px}.mini small{display:block;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.mini strong{display:block;font-size:21px;margin-top:5px}.float-card{position:absolute;z-index:2;left:0;bottom:34px;background:var(--lime);color:var(--lime-ink);padding:16px 18px;border-radius:16px;box-shadow:0 18px 40px rgba(0,0,0,.35);transform:rotate(-3deg)}.float-card small{display:block;font:700 10px/1 ui-monospace,SFMono-Regular,monospace;text-transform:uppercase;letter-spacing:.1em;opacity:.65}.float-card strong{display:block;font-size:18px;margin-top:6px}
    .workspace{margin-top:6px}.card{background:rgba(17,22,20,.94);border:1px solid var(--line);border-radius:var(--radius);padding:30px;box-shadow:0 18px 60px rgba(0,0,0,.18)}.card-head{display:flex;justify-content:space-between;gap:20px;align-items:start;margin-bottom:24px}.card h2{font-size:28px;line-height:1.1;letter-spacing:-.035em;margin:0}.card h3{font-size:17px;margin:0}.muted{color:var(--muted)}.card p{margin:8px 0 0}.hidden{display:none!important}.primary,.secondary,.ghost{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:12px;padding:12px 17px;font-weight:760;transition:.16s ease}.primary{background:var(--lime);color:var(--lime-ink)}.primary:hover{background:#d7ff78;transform:translateY(-1px)}.secondary{background:#202824;color:var(--ink);border:1px solid var(--line-bright)}.secondary:hover{border-color:#5a6961;background:#252f2a}.ghost{background:transparent;color:var(--muted);border:1px solid var(--line)}button:disabled{opacity:.5;cursor:not-allowed;transform:none!important}.field{margin-top:20px}.field label{display:block;color:var(--soft);font-weight:700;margin-bottom:8px}.field-row{display:flex;gap:10px}.field input{flex:1;min-width:0;border:1px solid var(--line-bright);background:#0c100e;color:var(--ink);border-radius:12px;padding:13px 14px;outline:none}.field input:focus{border-color:var(--lime);box-shadow:0 0 0 3px rgba(199,255,69,.09)}.message{min-height:22px;margin-top:10px!important}.ok{color:var(--lime);font-weight:700}.error{color:var(--red);font-weight:700}
    .access-card{max-width:650px;margin:0 auto;background:linear-gradient(145deg,rgba(22,29,26,.98),rgba(12,16,14,.98))}.invite-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:14px;background:rgba(199,255,69,.1);border:1px solid rgba(199,255,69,.2);color:var(--lime);font-size:22px;margin-bottom:24px}.owner{margin-top:24px;padding-top:20px;border-top:1px solid var(--line)}.owner summary{color:var(--muted);cursor:pointer;font-weight:650;list-style:none}.owner summary::-webkit-details-marker{display:none}.owner summary:after{content:" +";color:var(--lime)}
    .progress{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);border:1px solid var(--line);border-radius:18px;overflow:hidden;margin-bottom:18px}.step{position:relative;background:var(--panel);padding:20px}.step small{display:block;color:var(--muted);font:700 10px/1 ui-monospace,SFMono-Regular,monospace;text-transform:uppercase;letter-spacing:.1em;margin-bottom:9px}.step strong{display:block;font-size:15px}.step span{display:block;color:var(--muted);font-size:12px;margin-top:3px}.step.done{background:#182017}.step.done small,.step.done span{color:#94b166}.step.done:after{content:"✓";position:absolute;right:16px;top:18px;color:var(--lime);font-weight:900}
    .dashboard-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.provider-card{min-height:235px}.provider-top{display:flex;justify-content:space-between;align-items:start}.provider-logo{width:50px;height:50px;border-radius:15px;display:grid;place-items:center;background:#131f27;border:1px solid #253d4c;color:#5fc3ff;font-weight:900;font-size:21px}.status{display:inline-flex;align-items:center;gap:7px;border-radius:999px;border:1px solid var(--line);padding:6px 9px;color:var(--muted);font-size:11px;font-weight:750;text-transform:uppercase;letter-spacing:.07em}.status:before{content:"";width:6px;height:6px;border-radius:50%;background:#65716b}.status.online{color:var(--lime);border-color:rgba(199,255,69,.22);background:rgba(199,255,69,.05)}.status.online:before{background:var(--lime);box-shadow:0 0 10px var(--lime)}.provider-copy{margin:26px 0}.provider-copy h2{font-size:25px}.provider-copy p{max-width:460px}.clients{grid-column:1/-1}.client-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.client{border:1px solid var(--line);background:#0d1210;border-radius:16px;padding:18px}.client-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.client-title span{color:var(--muted);font:650 11px/1 ui-monospace,SFMono-Regular,monospace;text-transform:uppercase}.command{position:relative}.command pre{white-space:pre-wrap;word-break:break-all;min-height:100px;margin:0;background:#080b0a;border:1px solid #202824;border-radius:11px;padding:13px;color:#aeb9b3;font:12px/1.55 ui-monospace,SFMono-Regular,monospace}.command button{position:absolute;right:8px;top:8px;padding:7px 10px;font-size:11px;border-radius:8px}.success-note{display:flex;align-items:center;gap:10px;margin-top:18px!important;color:var(--soft)}.success-note:before{content:"→";display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:var(--lime);color:var(--lime-ink);font-weight:900}.owner-panel{grid-column:1/-1;background:linear-gradient(135deg,#171f1b,#111614)}.invite-output{margin-top:14px;padding:14px;border:1px dashed var(--line-bright);border-radius:12px;background:#0c100e;color:var(--soft);word-break:break-all;font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px}.history-list{display:grid;gap:10px;margin-top:20px}.history-row{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;padding:15px;border:1px solid var(--line);border-radius:13px;background:#0c100e}.history-row strong,.history-row span{display:block}.history-row span{color:var(--muted);font-size:12px;margin-top:3px}.history-actions{display:flex;gap:8px}.history-actions button,.history-actions a{padding:8px 10px;font-size:11px;text-decoration:none}.footer{display:flex;justify-content:space-between;gap:20px;padding:28px 0 0;color:#64706a;font-size:12px}.footer span:last-child{text-align:right}
    @media(max-width:900px){.hero{grid-template-columns:1fr;padding-top:58px}.visual{display:none}.dashboard-grid{grid-template-columns:1fr}.clients,.owner-panel{grid-column:auto}.client-grid{grid-template-columns:1fr}}
    @media(max-width:620px){.shell{padding:0 18px 40px}.topbar{height:68px}.topmeta .badge{display:none}.hero{padding:48px 0 38px}.hero h1{font-size:53px}.lead{font-size:17px}.card{padding:22px;border-radius:18px}.field-row{display:block}.field-row button{width:100%;margin-top:10px}.progress{grid-template-columns:1fr}.step{padding:15px}.client-grid{grid-template-columns:1fr}.footer{display:block}.footer span{display:block;margin-top:6px!important;text-align:left!important}}
  </style>
</head>
<body><div class="shell">
  <nav class="topbar"><div class="brand"><div class="mark">E</div><span>Endurance Bridge</span></div><div class="topmeta"><span class="badge">Private beta</span><a class="ghost" href="https://github.com/rogowoi/endurance-bridge">GitHub ↗</a></div></nav>

  <section class="hero"><div><div class="kicker">Endurance data × MCP</div><h1>Your training.<br><span>Finally fluent.</span></h1><p class="lead">Connect your training providers once. Then discuss sessions, weeks, recovery, plans, workouts, and routes with Codex or Claude.</p><div class="proof"><span>One clean toolset</span><span>Coverage-aware</span><span>Private accounts</span></div></div>
    <div class="visual" aria-hidden="true"><div class="device"><div class="device-head"><span>Weekly load</span><i></i></div><div class="metric"><div class="metric-label">Training volume</div><div class="metric-value">8.4<small>hours</small></div></div><div class="chart"><b style="height:34%"></b><b style="height:58%"></b><b style="height:42%"></b><b style="height:82%"></b><b style="height:67%"></b><b style="height:96%"></b><b style="height:74%"></b></div><div class="device-row"><div class="mini"><small>Distance</small><strong>124 km</strong></div><div class="mini"><small>Recovery</small><strong>Good</strong></div></div></div><div class="float-card"><small>Next session</small><strong>Tempo · 55 min</strong></div></div>
  </section>

  <main class="workspace">
    <section id="loading" class="card access-card"><div class="invite-icon">↻</div><h2>Preparing your dashboard</h2><p class="muted">Checking your private connection…</p></section>

    <section id="welcome" class="card access-card hidden"><div class="invite-icon">⌁</div><div class="card-head"><div><h2>Get an invitation</h2><p class="muted">Endurance Bridge is currently open to friends and early testers.</p></div><span class="badge">Invite only</span></div><p class="muted">Ask the owner for a personal link. It creates a private account just for you—no developer setup required.</p><details class="owner"><summary>Owner access</summary><div class="field"><label for="ownerKey">Owner key</label><div class="field-row"><input id="ownerKey" type="password" autocomplete="off" placeholder="Paste your owner key"><button id="ownerLogin" class="primary">Open dashboard</button></div><p id="ownerMessage" class="message"></p></div></details></section>

    <section id="join" class="card access-card hidden"><div class="invite-icon">→</div><div class="card-head"><div><h2>You’re invited.</h2><p class="muted">Create your private Endurance Bridge account.</p></div><span class="badge">1 of 3</span></div><div class="field"><label for="displayName">Your name</label><div class="field-row"><input id="displayName" autocomplete="name" maxlength="80" placeholder="How should we call you?"><button id="joinButton" class="primary">Continue</button></div><p id="joinMessage" class="message"></p></div></section>

    <section id="dashboard" class="hidden">
      <div class="progress"><div id="stepAccount" class="step done"><small>Step 01</small><strong>Account</strong><span id="accountName"></span></div><div id="stepGarmin" class="step"><small>Step 02</small><strong>Garmin</strong><span id="garminStepText">Connect account</span></div><div id="stepClient" class="step"><small>Step 03</small><strong>AI client</strong><span id="clientStepText">Copy one command</span></div></div>

      <div class="dashboard-grid"><section class="card provider-card"><div class="provider-top"><div class="provider-logo">G</div><span id="garminStatus" class="status">Not connected</span></div><div class="provider-copy"><h2 id="garminTitle">Connect Garmin</h2><p id="garminDescription" class="muted">Authorize once to unlock activities, health, workouts, schedules, and courses.</p></div><button id="garminButton" class="primary">Connect Garmin <span>→</span></button></section>

      <section class="card provider-card"><div class="provider-top"><div class="provider-logo" style="background:#1c1913;border-color:#403623;color:#f5b942">AI</div><span class="status">12 tools</span></div><div class="provider-copy"><h2>Ask about any period.</h2><p class="muted">Say: “Discuss my full last week.” Your AI loads activities, details, health context, plan, totals, provenance, and coverage in one request.</p></div><span class="proof"><span>Codex</span><span>Claude</span></span></section>

      <section id="clients" class="card clients hidden"><div class="card-head"><div><h2>Add your AI client</h2><p class="muted">Create a private connection key, then copy one command.</p></div><span class="badge">Step 03</span></div><div id="needKey"><button id="keyButton" class="primary">Create connection key</button><p class="muted">Creating a new key replaces the previous one.</p></div><div id="commands" class="hidden"><div class="client-grid"><div class="client"><div class="client-title"><h3>Codex</h3><span>macOS</span></div><div class="command"><pre id="codexCommand"></pre><button class="secondary" data-copy="codexCommand">Copy</button></div><p class="muted">After running it, fully quit Codex with ⌘Q and reopen it. Closing the window is not enough.</p></div><div class="client"><div class="client-title"><h3>Claude Code</h3><span>Anthropic</span></div><div class="command"><pre id="claudeCommand"></pre><button class="secondary" data-copy="claudeCommand">Copy</button></div></div></div><p id="successPrompt" class="success-note">Open a clean task, then ask: “Review today’s training.”</p></div></section>

      <section id="ownerPanel" class="card owner-panel hidden"><div class="card-head"><div><h2>Partner operations</h2><p class="muted">Invite people and prepare their Garmin history before they ask AI about older training.</p></div><span class="badge">Owner</span></div><button id="inviteButton" class="primary">Create invite link</button><div id="inviteOutput" class="invite-output hidden"></div><div id="historyRequests" class="history-list"></div></section></div>
    </section>
  </main>

  <footer class="footer"><span>Endurance Bridge · Open source</span><span>Separate account · Encrypted Garmin token · Revocable MCP key</span></footer>

  <script>
    const byId=(id)=>document.getElementById(id);const invite=new URLSearchParams(location.search).get('invite');
    async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Something went wrong');return body}
    function show(id){byId(id).classList.remove('hidden')}function hide(id){byId(id).classList.add('hidden')}
    function setKey(key){sessionStorage.setItem('enduranceApiKey',key)}
    function renderCommands(endpoint){const key=sessionStorage.getItem('enduranceApiKey');if(!key){show('needKey');hide('commands');return}hide('needKey');show('commands');byId('stepClient').classList.add('done');byId('clientStepText').textContent='Ready to add';byId('codexCommand').textContent="export ENDURANCE_BRIDGE_API_KEY='"+key+"'\\nlaunchctl setenv ENDURANCE_BRIDGE_API_KEY \\\"$ENDURANCE_BRIDGE_API_KEY\\\"\\ncodex mcp add endurance-bridge --url "+endpoint+" --bearer-token-env-var ENDURANCE_BRIDGE_API_KEY";const config=JSON.stringify({type:'http',url:endpoint,headers:{Authorization:'Bearer \${ENDURANCE_BRIDGE_API_KEY}'}});byId('claudeCommand').textContent="export ENDURANCE_BRIDGE_API_KEY='"+key+"'\\nclaude mcp add-json endurance-bridge '"+config+"' --scope user"}
    async function loadHistory(){const result=await api('/api/v1/admin');const pending=result.historyRequests.filter(item=>item.status!=='completed');byId('historyRequests').innerHTML=pending.length?pending.map(item=>'<div class="history-row"><div><strong>'+item.displayName+' · '+item.provider+'</strong><span>'+item.from.slice(0,10)+' → '+item.to.slice(0,10)+' · '+item.resources.join(', ')+' · user '+item.providerUserId+'</span></div><div class="history-actions"><a class="ghost" href="https://apis.garmin.com/tools/login" target="_blank">Open Garmin</a><button class="secondary history-ready" data-id="'+item.id+'">Mark ready</button></div></div>').join(''):'<p class="muted">No history requests waiting.</p>';document.querySelectorAll('.history-ready').forEach(button=>button.onclick=()=>markHistory(button.dataset.id))}
    async function markHistory(id){await api('/api/v1/admin',{method:'PATCH',body:JSON.stringify({action:'history',id,status:'completed'})});await loadHistory()}
    async function load(){try{const account=await api('/api/v1/account');hide('loading');hide('welcome');hide('join');show('dashboard');byId('accountName').textContent=account.user.displayName;if(account.user.isOwner){show('ownerPanel');await loadHistory()}if(account.garmin.connected){const history=account.garmin.history||{status:'not_requested'};const ready=history.status==='completed';byId('stepGarmin').classList.add('done');byId('garminStepText').textContent=ready?'Connected · history ready':'Connected · history loading';byId('garminTitle').textContent='Garmin connected';byId('garminDescription').textContent=ready?'Activities, health, workouts, calendar, and routes are ready.':'New sessions are live now. We’re preparing your recent activity and health history in the background.';byId('garminButton').innerHTML='Reconnect <span>↻</span>';byId('garminStatus').textContent=ready?'Ready':'History loading';byId('garminStatus').className=ready?'status online':'status';byId('successPrompt').textContent=ready?'Open a clean task, then ask: “Review my training from last week.”':'Open a clean task, then ask: “Review today’s training.” Older history will become available automatically.';show('clients');renderCommands(account.mcpEndpoint)}}catch{hide('loading');if(invite)show('join');else show('welcome')}}
    byId('ownerLogin').onclick=async()=>{try{await api('/api/v1/auth',{method:'POST',body:JSON.stringify({action:'owner',key:byId('ownerKey').value})});location.reload()}catch(error){byId('ownerMessage').textContent=error.message;byId('ownerMessage').className='message error'}};
    byId('joinButton').onclick=async()=>{try{const result=await api('/api/v1/auth',{method:'POST',body:JSON.stringify({action:'join',invite,displayName:byId('displayName').value})});setKey(result.apiKey);history.replaceState({},'',location.pathname);await load()}catch(error){byId('joinMessage').textContent=error.message;byId('joinMessage').className='message error'}};
    byId('garminButton').onclick=async()=>{byId('garminButton').disabled=true;try{const result=await api('/api/v1/setup/garmin/start',{method:'POST'});location.href=result.authorizationUrl}catch(error){byId('garminStatus').textContent=error.message;byId('garminStatus').className='error';byId('garminButton').disabled=false}};
    byId('keyButton').onclick=async()=>{try{const result=await api('/api/v1/account/key',{method:'POST'});setKey(result.apiKey);const account=await api('/api/v1/account');renderCommands(account.mcpEndpoint)}catch(error){alert(error.message)}};
    byId('inviteButton').onclick=async()=>{try{const result=await api('/api/v1/admin',{method:'POST',body:JSON.stringify({action:'invite'})});byId('inviteOutput').textContent=result.inviteUrl;show('inviteOutput');await navigator.clipboard.writeText(result.inviteUrl);byId('inviteButton').textContent='Invite copied ✓'}catch(error){byId('inviteOutput').textContent=error.message;show('inviteOutput')}};
    document.querySelectorAll('[data-copy]').forEach(button=>button.onclick=async()=>{await navigator.clipboard.writeText(byId(button.dataset.copy).textContent);button.textContent='Copied ✓'});
    load();
  </script>
</div></body></html>`;

export default function handler(request: VercelRequest, response: VercelResponse) {
  if (request.method !== "GET") {
    response.setHeader("Allow", "GET");
    return response.status(405).send("Method not allowed");
  }
  response.setHeader("Content-Type", "text/html; charset=utf-8");
  response.setHeader("Cache-Control", "no-store");
  return response.status(200).send(HTML);
}
